/**
 * Moinkee World Tour — location cards for the Digital Passport campaign.
 * fileName must match the actual file in your IPFS folder.
 * Set NEXT_PUBLIC_FOLDER_CID in .env.local to your Pinata folder CID.
 */

export const FOLDER_CID =
  process.env.NEXT_PUBLIC_FOLDER_CID ||
  "bafybeig65m3sqqp7ant5fn7soc77eaurjoepjgdwywjedydvett5fa7fbi";

export const MOINKEE_LOCATIONS = [
  {
    id: "abudhabi",
    event: "Abu Dhabi Finance Week",
    location: "Abu Dhabi, UAE",
    region: "MENA",
    lat: 24.4539,
    lng: 54.3773,
    fileName: "AbuDhabi.jpg",
    description: "Where traditional finance meets decentralized innovation. Moinkee landed in Abu Dhabi for the region's premier financial summit.",
  },
  {
    id: "amsterdam",
    event: "ETHAmsterdam",
    location: "Amsterdam, NL",
    region: "Europe",
    lat: 52.3676,
    lng: 4.9041,
    fileName: "Amsterdam.jpg",
    description: "Canals, bikes, and blockchain. Moinkee explored the Dutch Web3 scene at ETHAmsterdam. Your tulip-coded memento.",
  },
  {
    id: "athens",
    event: "ETHAthens",
    location: "Athens, GR",
    region: "Europe",
    lat: 37.9838,
    lng: 23.7275,
    fileName: "Athens.jpg",
    description: "Birthplace of democracy, birthplace of decentralization. Moinkee visited the Acropolis of Web3 at ETHAthens.",
  },
  {
    id: "auckland",
    event: "NZ Blockchain Summit",
    location: "Auckland, NZ",
    region: "Asia",
    lat: -36.8485,
    lng: 174.7633,
    fileName: "Auckland.jpg",
    description: "From Middle-earth to the metaverse. Moinkee touched down in Auckland for the Southern Hemisphere's Web3 gathering.",
  },
  {
    id: "barcelona",
    event: "ETHBarcelona",
    location: "Barcelona, ES",
    region: "Europe",
    lat: 41.3874,
    lng: 2.1686,
    fileName: "Barcelona.jpg",
    description: "Sun, tapas, and smart contracts. Moinkee hit Barcelona for a week of Ethereum culture on the Mediterranean.",
  },
  {
    id: "base",
    event: "Base Ecosystem",
    location: "Onchain",
    region: "Onchain",
    lat: 37.7749,
    lng: -122.4194,
    fileName: "Base.jpg",
    description: "Moinkee went onchain with Base. A memento from the frontier of L2 innovation.",
  },
  {
    id: "beijing",
    event: "Beijing Web3 Forum",
    location: "Beijing, CN",
    region: "Asia",
    lat: 39.9042,
    lng: 116.4074,
    fileName: "Beijing.jpg",
    description: "The Great Wall of decentralization. Moinkee visited Beijing for Asia's most ambitious blockchain forum.",
  },
  {
    id: "bengaluru",
    event: "ETHIndia",
    location: "Bengaluru, IN",
    region: "Asia",
    lat: 12.9716,
    lng: 77.5946,
    fileName: "Bengaluru.jpg",
    description: "India's Silicon Valley goes Web3. Moinkee was at ETHIndia in Bengaluru — the largest Ethereum hackathon in Asia.",
  },
  {
    id: "berlin",
    event: "ETHBerlin",
    location: "Berlin, DE",
    region: "Europe",
    lat: 52.52,
    lng: 13.405,
    fileName: "Berlin.jpg",
    description: "Techno and tech. Moinkee hacked at ETHBerlin — Europe's most iconic crypto-native city.",
  },
  {
    id: "bogota",
    event: "Devcon Bogotá",
    location: "Bogotá, CO",
    region: "LatAm",
    lat: 4.711,
    lng: -74.0721,
    fileName: "Bogota.jpg",
    description: "Devcon came to Latin America and Moinkee was there. A memento from Bogotá's historic Ethereum gathering.",
  },
  {
    id: "boston",
    event: "Boston Blockchain Week",
    location: "Boston, MA",
    region: "North America",
    lat: 42.3601,
    lng: -71.0589,
    fileName: "Boston.jpg",
    description: "Where academia meets the chain. Moinkee explored Boston's blockchain scene between MIT and the harbor.",
  },
  {
    id: "buenosaires",
    event: "ETHLatam",
    location: "Buenos Aires, AR",
    region: "LatAm",
    lat: -34.6037,
    lng: -58.3816,
    fileName: "BuenosAires.jpg",
    description: "Tango and tokens. Moinkee danced through ETHLatam in Buenos Aires — Latin America's crypto capital.",
  },
  {
    id: "cairo",
    event: "Cairo Web3 Summit",
    location: "Cairo, EG",
    region: "MENA",
    lat: 30.0444,
    lng: 31.2357,
    fileName: "Cairo.jpg",
    description: "From the pyramids to the protocol. Moinkee visited Cairo where ancient civilization meets onchain innovation.",
  },
  {
    id: "cannes",
    event: "EthCC",
    location: "Cannes, FR",
    region: "Europe",
    lat: 43.5528,
    lng: 7.0174,
    fileName: "Cannes.jpg",
    description: "Web3 on the Riviera. Moinkee hit EthCC in Cannes for a week of talks, sun, and on-chain culture.",
  },
  {
    id: "capetown",
    event: "Africa Blockchain Summit",
    location: "Cape Town, ZA",
    region: "Africa",
    lat: -33.9249,
    lng: 18.4241,
    fileName: "CapeTown.jpg",
    description: "Table Mountain meets the decentralized future. Moinkee visited Cape Town for Africa's premier blockchain summit.",
  },
  {
    id: "chennai",
    event: "Chennai Blockchain Meetup",
    location: "Chennai, IN",
    region: "Asia",
    lat: 13.0827,
    lng: 80.2707,
    fileName: "Chennai.jpg",
    description: "South India's tech hub joins the Web3 wave. Moinkee visited Chennai where temples and tech collide.",
  },
  {
    id: "chicago",
    event: "DeFi Summit Chicago",
    location: "Chicago, IL",
    region: "North America",
    lat: 41.8781,
    lng: -87.6298,
    fileName: "Chicago.jpg",
    description: "The Windy City blows in a new financial era. Moinkee was at Chicago's DeFi Summit on the shores of Lake Michigan.",
  },
  {
    id: "copenhagen",
    event: "Copenhagen Blockchain Week",
    location: "Copenhagen, DK",
    region: "Europe",
    lat: 55.6761,
    lng: 12.5683,
    fileName: "Copenhagen.jpg",
    description: "Nordic innovation meets decentralization. Moinkee explored Copenhagen's progressive blockchain community.",
  },
  {
    id: "davos",
    event: "WEF Davos",
    location: "Davos, CH",
    region: "Europe",
    lat: 46.8003,
    lng: 9.8361,
    fileName: "Davos.jpg",
    description: "From the World Economic Forum to Web3. Moinkee brought decentralization to the Swiss Alps at Davos.",
  },
  {
    id: "delhi",
    event: "Delhi Blockchain Summit",
    location: "New Delhi, IN",
    region: "Asia",
    lat: 28.6139,
    lng: 77.209,
    fileName: "Dehli.jpg",
    description: "India's capital enters the onchain era. Moinkee visited Delhi where a billion-person Web3 market is being built.",
  },
  {
    id: "dubai",
    event: "Token2049 Dubai",
    location: "Dubai, UAE",
    region: "MENA",
    lat: 25.2048,
    lng: 55.2708,
    fileName: "Dubai.jpg",
    description: "From the desert to the main stage. Moinkee was at Token2049 Dubai where the future of crypto is being shaped.",
  },
  {
    id: "dublin",
    event: "Dublin Blockchain Week",
    location: "Dublin, IE",
    region: "Europe",
    lat: 53.3498,
    lng: -6.2603,
    fileName: "Dublin.jpg",
    description: "The luck of the chain. Moinkee visited Dublin for Ireland's growing blockchain community. Sláinte to Web3.",
  },
  {
    id: "ethdenver",
    event: "ETHDenver",
    location: "Denver, CO",
    region: "North America",
    lat: 39.7392,
    lng: -104.9903,
    fileName: "EthDenver.jpg",
    description: "Moinkee touched down at ETHDenver — the world's largest and longest-running Ethereum hackathon. BUIDL in the Rockies.",
  },
  {
    id: "hongkong",
    event: "Hong Kong Web3 Festival",
    location: "Hong Kong",
    region: "Asia",
    lat: 22.3193,
    lng: 114.1694,
    fileName: "HongKong.jpg",
    description: "Asia's World City goes onchain. Moinkee was at the Hong Kong Web3 Festival where East meets decentralized.",
  },
  {
    id: "istanbul",
    event: "Devconnect Istanbul",
    location: "Istanbul, TR",
    region: "MENA",
    lat: 41.0082,
    lng: 28.9784,
    fileName: "Istanbul.jpg",
    description: "Where continents collide. Moinkee visited Devconnect Istanbul — bridging Europe and Asia through Ethereum.",
  },
  {
    id: "korea",
    event: "Korea Blockchain Week",
    location: "Seoul, KR",
    region: "Asia",
    lat: 37.5665,
    lng: 126.978,
    fileName: "Korea.jpg",
    description: "East meets decentralized. Korea Blockchain Week brought Moinkee to Seoul. Your digital passport got a K-stamp.",
  },
  {
    id: "la",
    event: "LA Blockchain Summit",
    location: "Los Angeles, CA",
    region: "North America",
    lat: 34.0522,
    lng: -118.2437,
    fileName: "LA.jpg",
    description: "Hollywood meets the blockchain. Moinkee went to LA where entertainment and Web3 are writing the next script.",
  },
  {
    id: "lagos",
    event: "Lagos Blockchain Conference",
    location: "Lagos, NG",
    region: "Africa",
    lat: 6.5244,
    lng: 3.3792,
    fileName: "Lagos.jpg",
    description: "Africa's most populous city goes Web3. Moinkee visited Lagos — the heart of the continent's crypto revolution.",
  },
  {
    id: "lisbon",
    event: "NearCon Lisbon",
    location: "Lisbon, PT",
    region: "Europe",
    lat: 38.7223,
    lng: -9.1393,
    fileName: "Lisbon.jpg",
    description: "Sun, sardines, and scalability. Moinkee explored Lisbon's thriving crypto-nomad scene. A Portuguese stamp for your passport.",
  },
  {
    id: "london",
    event: "London Blockchain Conference",
    location: "London, UK",
    region: "Europe",
    lat: 51.5074,
    lng: -0.1278,
    fileName: "London.jpg",
    description: "From the City to the chain. Moinkee visited London where centuries of finance meet the decentralized future.",
  },
  {
    id: "madrid",
    event: "ETHMadrid",
    location: "Madrid, ES",
    region: "Europe",
    lat: 40.4168,
    lng: -3.7038,
    fileName: "Madrid.jpg",
    description: "¡Olé onchain! Moinkee arrived in Madrid for Spain's Ethereum community gathering in the heart of Iberia.",
  },
  {
    id: "melbourne",
    event: "Melbourne Blockchain Week",
    location: "Melbourne, AU",
    region: "Asia",
    lat: -37.8136,
    lng: 144.9631,
    fileName: "Melbourne.jpg",
    description: "Down under, onchain. Moinkee surfed into Melbourne for Australia's leading blockchain event.",
  },
  {
    id: "miami",
    event: "Bitcoin Miami",
    location: "Miami, FL",
    region: "North America",
    lat: 25.7617,
    lng: -80.1918,
    fileName: "Miami.jpg",
    description: "Neon lights and digital assets. Moinkee hit Miami Beach for the crypto conference that never sleeps.",
  },
  {
    id: "milan",
    event: "Milan Web3 Week",
    location: "Milan, IT",
    region: "Europe",
    lat: 45.4642,
    lng: 9.19,
    fileName: "Milan.jpg",
    description: "Fashion capital meets DeFi capital. Moinkee walked the runway of Web3 innovation in Milan.",
  },
  {
    id: "monaco",
    event: "Blockchain Monaco",
    location: "Monaco",
    region: "Europe",
    lat: 43.7384,
    lng: 7.4246,
    fileName: "Monaco.jpg",
    description: "High stakes, higher blocks. Moinkee visited Monaco where luxury meets decentralized finance on the Côte d'Azur.",
  },
  {
    id: "mumbai",
    event: "Mumbai Web3 Summit",
    location: "Mumbai, IN",
    region: "Asia",
    lat: 19.076,
    lng: 72.8777,
    fileName: "Mumbai.jpg",
    description: "Bollywood meets blockchain. Moinkee visited Mumbai — India's financial capital embracing the onchain future.",
  },
  {
    id: "nyc",
    event: "NFT.NYC / Mainnet",
    location: "New York, NY",
    region: "North America",
    lat: 40.7128,
    lng: -74.006,
    fileName: "NYC.jpg",
    description: "The city that never sleeps, now onchain. Moinkee was in NYC for the intersection of culture and crypto.",
  },
  {
    id: "nairobi",
    event: "Nairobi Blockchain Summit",
    location: "Nairobi, KE",
    region: "Africa",
    lat: -1.2921,
    lng: 36.8219,
    fileName: "Nairobi.jpg",
    description: "The savannah goes digital. Moinkee visited Nairobi — East Africa's tech hub leading the Web3 charge.",
  },
  {
    id: "oxford",
    event: "Oxford Blockchain Conference",
    location: "Oxford, UK",
    region: "Europe",
    lat: 51.752,
    lng: -1.2577,
    fileName: "Oxford.jpg",
    description: "From ivory towers to decentralized protocols. Moinkee visited Oxford where academia drives blockchain research.",
  },
  {
    id: "rabat",
    event: "Rabat Blockchain Forum",
    location: "Rabat, MA",
    region: "Africa",
    lat: 34.0209,
    lng: -6.8416,
    fileName: "Rabat.jpg",
    description: "North Africa enters the chain. Moinkee visited Rabat where Morocco's tech community is building the future.",
  },
  {
    id: "reykjavik",
    event: "Iceland Blockchain Forum",
    location: "Reykjavik, IS",
    region: "Europe",
    lat: 64.1466,
    lng: -21.9426,
    fileName: "Reykjavjik.jpg",
    description: "Fire, ice, and consensus. Moinkee visited Reykjavik — where geothermal energy powers the blockchain.",
  },
  {
    id: "rio",
    event: "Rio Blockchain Week",
    location: "Rio de Janeiro, BR",
    region: "LatAm",
    lat: -22.9068,
    lng: -43.1729,
    fileName: "Rio.jpg",
    description: "Samba and smart contracts. Moinkee danced into Rio for Brazil's vibrant blockchain community.",
  },
  {
    id: "sanfrancisco",
    event: "SF Blockchain Week",
    location: "San Francisco, CA",
    region: "North America",
    lat: 37.7749,
    lng: -122.4194,
    fileName: "SanFrancisco.jpg",
    description: "Silicon Valley's crypto chapter. Moinkee was in San Francisco where VCs and validators shape the future.",
  },
  {
    id: "santiago",
    event: "Santiago Blockchain Summit",
    location: "Santiago, CL",
    region: "LatAm",
    lat: -33.4489,
    lng: -70.6693,
    fileName: "Santiago.jpg",
    description: "The Andes and the ledger. Moinkee visited Santiago where Chile's tech scene is embracing decentralization.",
  },
  {
    id: "shanghai",
    event: "Shanghai Web3 Festival",
    location: "Shanghai, CN",
    region: "Asia",
    lat: 31.2304,
    lng: 121.4737,
    fileName: "Shanghai.jpg",
    description: "The Pearl of the Orient goes onchain. Moinkee explored Shanghai's bustling Web3 ecosystem.",
  },
  {
    id: "singapore",
    event: "Token2049 Singapore",
    location: "Singapore",
    region: "Asia",
    lat: 1.3521,
    lng: 103.8198,
    fileName: "Singapore.jpg",
    description: "The Lion City roared for Web3. Moinkee was at Token2049 Singapore — Asia's premier crypto summit.",
  },
  {
    id: "sydney",
    event: "Sydney Blockchain Week",
    location: "Sydney, AU",
    region: "Asia",
    lat: -33.8688,
    lng: 151.2093,
    fileName: "Sydeny.jpg",
    description: "The harbor city goes decentralized. Moinkee caught the wave in Sydney for Australia's Web3 community.",
  },
  {
    id: "tokyo",
    event: "ETHTokyo",
    location: "Tokyo, JP",
    region: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    fileName: "Tokyo.jpg",
    description: "Neon lights and zero-knowledge proofs. Moinkee was at ETHTokyo — where Japanese precision meets Ethereum.",
  },
  {
    id: "toronto",
    event: "Consensus",
    location: "Toronto, CA",
    region: "North America",
    lat: 43.6532,
    lng: -79.3832,
    fileName: "Toronto.jpg",
    description: "Consensus 2026 — where the industry meets. Moinkee joined the biggest names in Web3 in Toronto.",
  },
  {
    id: "uae",
    event: "UAE Blockchain Summit",
    location: "UAE",
    region: "MENA",
    lat: 24.4539,
    lng: 54.6474,
    fileName: "UAE.jpg",
    description: "The Emirates bet big on Web3. Moinkee toured the UAE for the region's most ambitious blockchain summit.",
  },
  {
    id: "vegas",
    event: "CES / Vegas Blockchain",
    location: "Las Vegas, NV",
    region: "North America",
    lat: 36.1699,
    lng: -115.1398,
    fileName: "Vegas.jpg",
    description: "What happens in Vegas gets minted on MOI. Moinkee hit the strip for blockchain's biggest desert party.",
  },
];
